language: objective-c
osx_image: xcode12.2

before_script:
    - travis_wait ./Scripts/carthage.sh bootstrap

script:
    # Build Travis project and run tests
    - xcodebuild -project LibreDirect.xcodeproj -scheme Shared build -destination name="iPhone 8" test 
